function html(): string {
  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<meta name="theme-color" content="#0b0e13" />
<title>Job Agent — مركز القيادة</title>
<style>
:root{color-scheme:dark;--bg:#080a0e;--panel:#10141b;--panel2:#141922;--line:#242b36;--muted:#8c97a6;--text:#f4f7fb;--accent:#7c5cff;--green:#35d07f;--amber:#f2b84b;--red:#ff5d68;--blue:#55a8ff;--shadow:0 18px 50px rgba(0,0,0,.28)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 85% 0,#18142e 0,#0b0e13 30%,var(--bg) 65%);color:var(--text);font:15px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button{cursor:pointer}.hidden{display:none!important}
.shell{display:grid;grid-template-columns:240px minmax(0,1fr);min-height:100vh}.side{border-left:1px solid var(--line);padding:24px 16px;background:rgba(9,12,17,.82);backdrop-filter:blur(18px);position:sticky;top:0;height:100vh}.brand{display:flex;align-items:center;gap:11px;padding:8px 10px 28px}.logo{width:40px;height:40px;border-radius:13px;background:linear-gradient(135deg,#8a6cff,#5b42d6);display:grid;place-items:center;font-size:21px;box-shadow:0 10px 25px #5d45d933}.brand b{display:block;font-size:17px}.brand span{display:block;color:var(--muted);font-size:11px}.nav{display:grid;gap:7px}.nav button{border:1px solid transparent;background:transparent;color:#aab3bf;text-align:right;padding:11px 12px;border-radius:11px}.nav button.active,.nav button:hover{background:#171c25;border-color:var(--line);color:#fff}.side-bottom{position:absolute;bottom:18px;right:16px;left:16px}.security{border:1px solid #27313d;background:#0e1319;border-radius:14px;padding:12px;font-size:12px;color:var(--muted)}.security strong{color:var(--green)}
.main{min-width:0;padding:28px clamp(16px,4vw,48px) 90px}.top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:24px}.eyebrow{color:var(--accent);font-weight:800;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.top h1{font-size:30px;margin:2px 0 0}.top p{margin:2px 0;color:var(--muted)}.top-actions{display:flex;gap:8px}.iconbtn{border:1px solid var(--line);background:var(--panel);color:#fff;border-radius:12px;padding:10px 12px}.primary{border:0;background:linear-gradient(135deg,#8a6cff,#6547dd);color:white;font-weight:800;border-radius:12px;padding:11px 15px;box-shadow:0 10px 24px #6346d933}.danger{background:#261419;border:1px solid #4a242d;color:#ff9aa2}
.hero{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(260px,.6fr);gap:14px}.hero-card,.card{background:linear-gradient(180deg,rgba(20,25,34,.96),rgba(13,17,23,.96));border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow)}.hero-card{padding:22px}.hero-card h2{font-size:23px;margin:0 0 7px}.hero-card p{color:var(--muted);margin:0 0 20px;max-width:680px}.runbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.runbar input,.runbar select{background:#0b0f15;border:1px solid #303845;color:#fff;border-radius:11px;padding:11px 12px;min-width:110px}.status-card{padding:20px}.status-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.pill{display:inline-flex;align-items:center;gap:7px;padding:6px 9px;border-radius:999px;background:#171d26;border:1px solid var(--line);font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:#77818e}.dot.green{background:var(--green);box-shadow:0 0 13px #35d07f99}.dot.amber{background:var(--amber);box-shadow:0 0 13px #f2b84b88}.dot.red{background:var(--red);box-shadow:0 0 13px #ff5d6888}.status-big{font-size:24px;font-weight:900;margin:22px 0 2px}.muted{color:var(--muted)}.tiny{font-size:12px;color:var(--muted)}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:14px 0}.stat{padding:17px}.stat .label{font-size:12px;color:var(--muted)}.stat .value{font-size:28px;font-weight:900;margin-top:5px}.stat .hint{font-size:11px;color:#76818e;margin-top:2px}.grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(300px,.6fr);gap:14px}.card{padding:19px}.card-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:15px}.card-head h3{margin:0;font-size:16px}.card-head span{font-size:12px;color:var(--muted)}
.pipeline{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.stage{position:relative;padding:12px 10px;background:#0d1117;border:1px solid var(--line);border-radius:12px;min-height:90px}.stage:after{content:'›';position:absolute;left:-8px;top:31px;color:#596371;font-size:17px}.stage:first-child:after{display:none}.stage .n{font-size:11px;color:var(--muted)}.stage b{display:block;margin-top:4px}.stage small{display:block;color:#737e8d;margin-top:5px;font-size:10px}.stage.active{border-color:#6e57e9;background:#16142a}.stage.done{border-color:#26553d}.stage .check{color:var(--green)}
.platforms{display:grid;gap:9px}.platform{display:flex;align-items:center;gap:11px;padding:12px;border:1px solid var(--line);background:#0d1117;border-radius:13px}.platform-icon{width:34px;height:34px;border-radius:10px;background:#1b212b;display:grid;place-items:center;font-weight:900}.platform b{display:block}.platform span{font-size:11px;color:var(--muted)}.platform .right{margin-right:auto;text-align:left}.badge-ok{color:var(--green)}.badge-warn{color:var(--amber)}
.runs{display:grid;gap:8px}.run{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:12px;border-bottom:1px solid #1d232d}.run:last-child{border-bottom:0}.run-main b{display:block}.run-main span{font-size:11px;color:var(--muted)}.run-status{font-size:11px;padding:5px 8px;border-radius:999px;background:#171d25;border:1px solid var(--line)}.run-status.success{color:var(--green)}.run-status.failed{color:var(--red)}.run-status.running{color:var(--blue)}
.log{background:#080b10;border:1px solid #202630;border-radius:12px;padding:12px;color:#9da8b6;font:12px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:90px;white-space:pre-wrap}.notice{padding:12px 13px;border-radius:12px;background:#121822;border:1px solid #26303b;color:#9ca8b5;font-size:12px}.notice strong{color:#fff}.modal{position:fixed;inset:0;background:#0009;backdrop-filter:blur(10px);display:grid;place-items:center;padding:18px;z-index:20}.modal-card{width:min(480px,100%);background:#11161e;border:1px solid #303845;border-radius:20px;padding:22px;box-shadow:0 30px 90px #0008}.modal-card h2{margin:0 0 5px}.modal-card p{color:var(--muted);margin:0 0 18px}.field{margin:13px 0}.field label{display:block;color:#b8c1cc;font-size:12px;margin-bottom:6px}.field input,.field select{width:100%;background:#0b0f15;border:1px solid #343d49;color:#fff;border-radius:11px;padding:12px}.modal-actions{display:flex;gap:9px;margin-top:18px}.modal-actions button{flex:1}.secondary{background:#1a2029;border:1px solid #303845;color:#fff;border-radius:11px;padding:11px}.login{min-height:100vh;display:grid;place-items:center;padding:18px}.login-card{width:min(420px,100%);padding:26px;background:#10141b;border:1px solid var(--line);border-radius:22px;box-shadow:var(--shadow)}.login-card .logo{margin-bottom:18px}.login-card h1{margin:0 0 6px}.login-card p{color:var(--muted);font-size:13px;margin:0 0 20px}.error{color:#ff8f98;font-size:12px;margin-top:8px}.mobile-nav{display:none}
@media(max-width:900px){.shell{display:block}.side{display:none}.main{padding:20px 14px 90px}.hero,.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.pipeline{grid-template-columns:1fr 1fr}.stage:after{display:none}.top h1{font-size:25px}.mobile-nav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;bottom:0;right:0;left:0;background:#0b0e13ee;border-top:1px solid var(--line);backdrop-filter:blur(18px);padding:8px 10px calc(8px + env(safe-area-inset-bottom));z-index:15}.mobile-nav button{background:transparent;border:0;color:#7f8997;font-size:11px;padding:6px}.mobile-nav button.active{color:#fff}.top-actions .desktop{display:none}}
@media(max-width:520px){.hero-card{padding:18px}.runbar{display:grid;grid-template-columns:1fr 1fr}.runbar .primary{grid-column:1/-1}.runbar input,.runbar select{width:100%;min-width:0}.stats{gap:8px}.stat{padding:13px}.stat .value{font-size:23px}.pipeline{grid-template-columns:1fr}.pipeline .stage{min-height:auto}.top{align-items:flex-start}.top-actions{display:grid}.top-actions .primary{padding:9px 11px}}
</style>
</head>
<body>
<div id="login" class="login">
  <div class="login-card">
    <div class="logo">🤖</div>
    <div class="eyebrow">JOB AGENT</div>
    <h1>مركز القيادة</h1>
    <p>جلسة آمنة للتحكم في وكيل التقديم ومتابعة التشغيل. المفتاح لا يُحفظ في المتصفح؛ بعد تسجيل الدخول نستخدم جلسة HttpOnly.</p>
    <div class="field"><label>مفتاح التحكم</label><input id="token" type="password" autocomplete="current-password" placeholder="أدخل مفتاح التحكم" /></div>
    <button id="loginBtn" class="primary" style="width:100%">دخول آمن</button>
    <div id="loginError" class="error"></div>
  </div>
</div>
<div id="app" class="shell hidden">
  <aside class="side">
    <div class="brand"><div class="logo">🤖</div><div><b>Job Agent</b><span>Autonomous workspace</span></div></div>
    <nav class="nav"><button class="active">⌂ &nbsp; مركز القيادة</button><button>◉ &nbsp; فرص العمل</button><button>▣ &nbsp; الطلبات</button><button>⚙ &nbsp; الإعدادات</button></nav>
    <div class="side-bottom"><div class="security">حالة الأمان<br><strong>● الجلسة محمية</strong><br><span>آخر تحديث تلقائي كل 10 ثوانٍ</span></div></div>
  </aside>
  <main class="main">
    <header class="top">
      <div><div class="eyebrow">AUTONOMOUS JOB SEARCH</div><h1>مركز القيادة</h1><p>من البحث والمطابقة إلى التقديم والتتبع — في شاشة واحدة.</p></div>
      <div class="top-actions"><button id="refresh" class="iconbtn desktop">↻ تحديث</button><button id="logout" class="iconbtn">خروج</button></div>
    </header>

    <section class="hero">
      <div class="hero-card">
        <div class="eyebrow">AGENT CONTROL</div><h2>شغّل دورة بحث جديدة</h2>
        <p>ابدأ بعدد صغير أولاً. الوكيل يمر عبر البحث، إزالة التكرار، المطابقة بالـAI، ثم التطبيق حسب الوضع الذي تختاره.</p>
        <div class="runbar"><input id="max" type="number" min="1" max="20" value="1" aria-label="عدد الطلبات"/><select id="mode" aria-label="وضع التشغيل"><option value="semi_automated">شبه آلي — مراجعة</option><option value="fully_automated">آلي بالكامل</option></select><button id="start" class="primary">▶ تشغيل الوكيل</button></div>
      </div>
      <div class="status-card card"><div class="status-head"><span class="pill"><i id="dot" class="dot"></i><span id="statusPill">جاهز</span></span><span class="tiny" id="lastUpdate">—</span></div><div class="status-big" id="statusBig">جاهز للتشغيل</div><div class="muted" id="statusDetail">لم تبدأ دورة بعد.</div><div style="margin-top:18px"><button id="stop" class="secondary danger" style="width:100%">■ إيقاف التشغيل</button></div></div>
    </section>

    <section class="stats"><div class="card stat"><div class="label">إجمالي التشغيلات</div><div id="runs" class="value">—</div><div class="hint">آخر الدورات</div></div><div class="card stat"><div class="label">ناجحة</div><div id="success" class="value">—</div><div class="hint">workflow مكتمل</div></div><div class="card stat"><div class="label">فاشلة</div><div id="failed" class="value">—</div><div class="hint">تحتاج فحص</div></div><div class="card stat"><div class="label">الحالة</div><div id="health" class="value" style="font-size:20px">● جاهز</div><div class="hint">GitHub Actions</div></div></section>

    <section class="grid">
      <div class="card"><div class="card-head"><h3>خط سير الوكيل</h3><span>Architecture</span></div><div class="pipeline"><div class="stage done"><div class="n">01</div><b>Profile</b><small class="check">✓ البيانات</small></div><div class="stage done"><div class="n">02</div><b>Discover</b><small class="check">✓ البحث</small></div><div id="stageMatch" class="stage"><div class="n">03</div><b>Match AI</b><small>مطابقة الوظائف</small></div><div id="stageApply" class="stage"><div class="n">04</div><b>Apply</b><small>ملء النماذج</small></div><div id="stageTrack" class="stage"><div class="n">05</div><b>Track</b><small>حفظ النتائج</small></div></div><div class="notice" style="margin-top:12px"><strong>قاعدة التشغيل:</strong> لا نرفع العدد تلقائياً. نبدأ بـ1، نراقب النتيجة، ثم يمكن رفع السعة تدريجياً.</div></div>
      <div class="card"><div class="card-head"><h3>مصادر التوظيف</h3><span>Connectors</span></div><div class="platforms"><div class="platform"><div class="platform-icon">IS</div><div><b>Internshala</b><span>Internships + Jobs</span></div><div class="right badge-ok">● Agent</div></div><div class="platform"><div class="platform-icon">N</div><div><b>Naukri</b><span>Jobs + profile</span></div><div class="right badge-ok">● Agent</div></div><div class="platform"><div class="platform-icon">ATS</div><div><b>ATS forms</b><span>طبقة التقديم</span></div><div class="right badge-warn">◐ حسب الدعم</div></div></div></div>
    </section>

    <section class="card" style="margin-top:14px"><div class="card-head"><h3>آخر التشغيلات</h3><span id="historyHint">—</span></div><div id="runsList" class="runs"><div class="muted">جاري التحميل…</div></div></section>
    <section class="card" style="margin-top:14px"><div class="card-head"><h3>مراقبة مباشرة</h3><span>Diagnostics</span></div><div id="log" class="log">في انتظار بيانات الوكيل…</div></section>
  </main>
  <nav class="mobile-nav"><button class="active">⌂<br>الرئيسية</button><button>◉<br>الفرص</button><button>▣<br>الطلبات</button><button>⚙<br>الإعدادات</button></nav>
</div>
<div id="confirm" class="modal hidden"><div class="modal-card"><h2>تشغيل الوكيل؟</h2><p>سيبدأ تشغيل GitHub Actions. العدد الحالي <strong id="confirmMax">1</strong> والوضع <strong id="confirmMode">شبه آلي</strong>.</p><div class="notice">للأول: اختر 1. إذا نجح المسار كاملاً، نرفع السعة لاحقاً.</div><div class="modal-actions"><button id="cancelRun" class="secondary">إلغاء</button><button id="confirmRun" class="primary">تأكيد التشغيل</button></div></div></div>
<script>
const $=id=>document.getElementById(id);
let busy=false, lastRunId=null;
const labels={queued:'في الانتظار',in_progress:'يعمل الآن',completed:'مكتمل',requested:'تم الطلب',waiting:'انتظار',success:'نجاح',failure:'فشل',cancelled:'أُلغي'};
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ar',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function setDot(kind){$('dot').className='dot '+kind}
function runLabel(r){if(r.status==='completed')return r.conclusion==='success'?'نجاح':r.conclusion==='cancelled'?'أُلغي':'فشل';return labels[r.status]||r.status||'—'}
function runClass(r){if(r.status==='in_progress'||r.status==='queued')return 'running';if(r.conclusion==='success')return 'success';if(r.conclusion==='failure')return 'failed';return ''}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(r.status===401){showLogin();throw new Error('انتهت الجلسة')}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function showLogin(){$('login').classList.remove('hidden');$('app').classList.add('hidden')}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
async function checkAuth(){try{const d=await api('/api/auth');if(d.ok){showApp();await refreshAll()}else showLogin()}catch{showLogin()}}
function openConfirm(){const max=Math.max(1,Math.min(20,Number($('max').value||1)));$('max').value=max;$('confirmMax').textContent=max;$('confirmMode').textContent=$('mode').value==='fully_automated'?'آلي بالكامل':'شبه آلي';$('confirm').classList.remove('hidden')}
function closeConfirm(){$('confirm').classList.add('hidden')}
async function startRun(){if(busy)return;busy=true;closeConfirm();setDot('amber');$('statusPill').textContent='جارٍ التشغيل';$('statusBig').textContent='إرسال المهمة…';$('statusDetail').textContent='جاري إنشاء دورة GitHub Actions.';try{const d=await api('/api/control',{method:'POST',body:JSON.stringify({action:'start',max_applications:Number($('max').value),automation_mode:$('mode').value})});$('log').textContent='✓ '+(d.status||'queued')+' — تم إرسال أمر التشغيل.';await refreshAll()}catch(e){setDot('red');$('statusPill').textContent='خطأ';$('statusBig').textContent='تعذر التشغيل';$('statusDetail').textContent=e.message;$('log').textContent='ERROR: '+e.message}finally{busy=false}}
async function stopRun(){if(busy)return;busy=true;try{const d=await api('/api/control',{method:'POST',body:JSON.stringify({action:'stop'})});$('log').textContent='✓ '+(d.message||'تم إرسال طلب الإيقاف.');await refreshAll()}catch(e){$('log').textContent='ERROR: '+e.message}finally{busy=false}}
function renderHistory(data){const list=data.runs||[];$('runs').textContent=list.length;$('success').textContent=list.filter(r=>r.conclusion==='success').length;$('failed').textContent=list.filter(r=>r.conclusion==='failure').length;$('historyHint').textContent=list.length?'آخر '+list.length+' دورات':'لا توجد دورات';if(!list.length){$('runsList').innerHTML='<div class="muted">لا توجد تشغيلات حتى الآن.</div>';return}$('runsList').innerHTML=list.map(r=>`<div class="run"><div class="run-main"><b>Run #${r.id}</b><span>${fmtDate(r.created_at)} · ${r.event||'workflow_dispatch'}</span></div><div class="run-status ${runClass(r)}">${runLabel(r)}</div></div>`).join('')}
function renderControl(d){lastRunId=d.run_id||null;const running=d.status==='in_progress'||d.status==='queued'||d.status==='requested';if(running){setDot('green');$('statusPill').textContent='يعمل الآن';$('statusBig').textContent='الوكيل يعمل';$('statusDetail').textContent='الدورة قيد التنفيذ على GitHub Actions.';$('health').textContent='● يعمل';['stageMatch','stageApply'].forEach(id=>$(id).classList.add('active'))}else if(d.conclusion==='failure'){setDot('red');$('statusPill').textContent='فشل';$('statusBig').textContent='الدورة الأخيرة فشلت';$('statusDetail').textContent='افتح التشغيل من سجل GitHub للتفاصيل.';$('health').textContent='● يحتاج فحص'}else{setDot('green');$('statusPill').textContent='جاهز';$('statusBig').textContent=d.status==='completed'?'آخر دورة مكتملة':'جاهز للتشغيل';$('statusDetail').textContent=d.conclusion==='success'?'آخر دورة انتهت بنجاح.':'لا يوجد تشغيل نشط.';$('health').textContent='● جاهز'}$('lastUpdate').textContent=fmtDate(d.updated_at)}
async function refreshAll(){try{const [c,h]=await Promise.all([api('/api/control'),api('/api/history?limit=8')]);renderControl(c);renderHistory(h);if(c.url)$('log').innerHTML=`آخر تشغيل: <a href="${c.url}" target="_blank" rel="noreferrer" style="color:#8e7aff">فتح GitHub Actions ↗</a>`}catch(e){$('log').textContent='ERROR: '+e.message;$('health').textContent='● غير متصل'}}
$('loginBtn').onclick=async()=>{const token=$('token').value.trim();$('loginError').textContent='';if(!token){$('loginError').textContent='أدخل مفتاح التحكم.';return}$('loginBtn').disabled=true;try{const d=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'login',token})});if(!d.ok)throw new Error('فشل تسجيل الدخول');$('token').value='';showApp();await refreshAll()}catch(e){$('loginError').textContent=e.message==='Failed to fetch'?'تعذر الوصول إلى الخادم.':e.message}finally{$('loginBtn').disabled=false}};
$('token').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});$('start').onclick=openConfirm;$('confirmRun').onclick=startRun;$('cancelRun').onclick=closeConfirm;$('stop').onclick=stopRun;$('refresh').onclick=refreshAll;$('logout').onclick=async()=>{try{await api('/api/auth',{method:'POST',body:JSON.stringify({action:'logout'})})}finally{showLogin()}};
checkAuth();setInterval(()=>{if(!$('app').classList.contains('hidden'))refreshAll()},10000);
</script>
</body></html>`;
}

export async function GET(): Promise<Response> {
  return new Response(html(), { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
}
